import json

data = {
    "values": [
        { "language": "Python", "extension": ".py" },
        { "language": "JavaScript", "extension": ".js" },
        { "language": "Java", "extension": ".java" },
        { "language": "C", "extension": ".c" },
        { "language": "C++", "extension": ".cpp" },
        { "language": "C#", "extension": ".cs" },
        { "language": "Ruby", "extension": ".rb" },
        { "language": "PHP", "extension": ".php" },
        { "language": "Swift", "extension": ".swift" },
        { "language": "Objective-C", "extension": ".m" },
        { "language": "Kotlin", "extension": ".kt" },
        { "language": "Go", "extension": ".go" },
        { "language": "Rust", "extension": ".rs" },
        { "language": "TypeScript", "extension": ".ts" },
        { "language": "HTML", "extension": ".html" },
        { "language": "CSS", "extension": ".css" },
        { "language": "SQL", "extension": ".sql" },
        { "language": "Shell", "extension": ".sh" },
        { "language": "Perl", "extension": ".pl" },
        { "language": "Scala", "extension": ".scala" },
        { "language": "Haskell", "extension": ".hs" },
        { "language": "Lua", "extension": ".lua" },
        { "language": "MATLAB", "extension": ".m" },
        { "language": "R", "extension": ".r" },
        { "language": "VHDL", "extension": ".vhd" },
        { "language": "Verilog", "extension": ".v" },
        { "language": "Pascal", "extension": ".pas" },
        { "language": "Fortran", "extension": ".f90" },
        { "language": "Ada", "extension": ".adb" },
        { "language": "COBOL", "extension": ".cbl" },
        { "language": "Dart", "extension": ".dart" },
        { "language": "Elm", "extension": ".elm" },
        { "language": "F#", "extension": ".fs" },
        { "language": "Erlang", "extension": ".erl" },
        { "language": "Prolog", "extension": ".pl" },
        { "language": "Lisp", "extension": ".lisp" },
        { "language": "Scheme", "extension": ".scm" },
        { "language": "Groovy", "extension": ".groovy" },
        { "language": "OCaml", "extension": ".ml" },
        { "language": "Smalltalk", "extension": ".st" },
        { "language": "Solidity", "extension": ".sol" },
        { "language": "Julia", "extension": ".jl" },
        { "language": "Assembly", "extension": ".asm" },
        { "language": "Markdown", "extension": ".md" },
        { "language": "YAML", "extension": ".yaml" },
        { "language": "JSON", "extension": ".json" },
        { "language": "XML", "extension": ".xml" },
        { "language": "Tcl", "extension": ".tcl" },
        { "language": "VBScript", "extension": ".vbs" },
        { "language": "Batch", "extension": ".bat" }
    ]
}

